# Project: FUND.PROGRAMACION
# Makefile created by Dev-C++ 4.9.9.2

CPP  = mingw32-g++.exe
CC   = mingw32-gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o "Sin\ Nombre1.o" $(RES)
LINKOBJ  = main.o "Sin Nombre1.o" $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = FUND.PROGRAMACION
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before FUND.PROGRAMACION all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "FUND.PROGRAMACION" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

"Sin\ Nombre1.o": Sin\ Nombre1.cpp
	$(CPP) -c "Sin Nombre1.cpp" -o "Sin Nombre1.o" $(CXXFLAGS)
